// Generated by npm run generate-types from the feed definitions in config. Do not edit by hand.

import {Generated} from "kysely";

export interface AdditionalFixedLink {
  id: Generated<number>;
  mode: string;
  origin: string;
  destination: string;
  duration: number;
  start_time: string;
  end_time: string;
  priority: number;
  start_date: string | null;
  end_date: string | null;
  monday: number;
  tuesday: number;
  wednesday: number;
  thursday: number;
  friday: number;
  saturday: number;
  sunday: number;
}

export interface AdvanceTicket {
  id: Generated<number>;
  ticket_code: string;
  restriction_code: string | null;
  restriction_flag: string;
  toc_id: string | null;
  end_date: string;
  start_date: string;
  check_type: string;
  ap_data: string;
  booking_time: string | null;
}

export interface Alias {
  id: Generated<number>;
  station_name: string;
  station_alias: string;
}

export interface Association {
  id: Generated<number>;
  base_uid: string;
  assoc_uid: string;
  start_date: string;
  end_date: string;
  monday: number;
  tuesday: number;
  wednesday: number;
  thursday: number;
  friday: number;
  saturday: number;
  sunday: number;
  assoc_cat: string | null;
  assoc_date_ind: string | null;
  assoc_location: string;
  base_location_suffix: string;
  assoc_location_suffix: string;
  association_type: string | null;
  stp_indicator: string;
}

export interface Easement {
  id: Generated<number>;
  easement_ref: string;
  start_date: string;
  end_date: string;
  text_ref: string;
  easement_type: number;
  easement_class: number;
  category: number;
  monday: number | null;
  tuesday: number | null;
  wednesday: number | null;
  thursday: number | null;
  friday: number | null;
  saturday: number | null;
  sunday: number | null;
}

export interface EasementDetail {
  id: Generated<number>;
  easement_ref: string;
  detail_type: number;
  detail_code: string;
}

export interface EasementException {
  id: Generated<number>;
  easement_ref: string;
  exception_type: number;
  exception_code: string;
}

export interface EasementLocation {
  id: Generated<number>;
  easement_ref: string;
  location_code: string;
  location_modifier: number;
}

export interface EasementText {
  id: Generated<number>;
  text_ref: string;
  easement_text: string;
}

export interface EasementToc {
  id: Generated<number>;
  text_ref: string;
  toc: string;
}

export interface Fare {
  id: Generated<number>;
  flow_id: number;
  ticket_code: string;
  fare: number;
  restriction_code: string | null;
}

export interface FixedLink {
  id: Generated<number>;
  mode: string;
  origin: string;
  destination: string;
  duration: number;
}

export interface Flow {
  id: Generated<number>;
  origin_code: string;
  destination_code: string;
  route_code: string;
  status_code: string;
  usage_code: string;
  direction: string;
  end_date: string;
  start_date: string;
  toc: string;
  cross_london_ind: number;
  ns_disc_ind: number;
  publication_ind: string;
  flow_id: number;
}

export interface Link {
  id: Generated<number>;
  start_node: string;
  end_node: string;
  map_code: string;
}

export interface Location {
  id: Generated<number>;
  uic?: string;
  end_date: string;
  start_date: string;
  quote_date?: string;
  area_admin_code?: string;
  nlc?: string | null;
  description?: string;
  crs?: string | null;
  resv?: string;
  ers_country?: string | null;
  ers_code?: string | null;
  fare_group?: string | null;
  county?: string | null;
  pte_code?: string | null;
  zone_no?: string | null;
  zone_ind?: string | null;
  region?: string | null;
  hierarchy?: string | null;
  cc_desc_out?: string | null;
  cc_desc_rtn?: string | null;
  atb_desc_out?: string | null;
  atb_desc_rtn?: string | null;
  special_facilities?: string | null;
  lul_direction_ind?: string | null;
  lul_uts_mode?: string | null;
  lul_zone_1?: number | null;
  lul_zone_2?: number | null;
  lul_zone_3?: number | null;
  lul_zone_4?: number | null;
  lul_zone_5?: number | null;
  lul_zone_6?: number | null;
  lul_uts_london_stn?: string | null;
  uts_code?: string | null;
  uts_a_code?: string | null;
  uts_ptr_bias?: string | null;
  uts_offset?: string | null;
  uts_north?: string | null;
  uts_east?: string | null;
  uts_south?: string | null;
  uts_west?: string | null;
  uic_code?: string;
  nlc_code?: string;
  group_code?: string;
  crs_code?: string | null;
  county_code?: string;
  zone_code?: string | null;
}

export interface LocationAssociation {
  id: Generated<number>;
  uic_code: string;
  end_date: string;
  assoc_uic_code: string;
  assoc_crs_code: string;
}

export interface LocationGroup {
  id: Generated<number>;
  group_uic_code: string;
  end_date: string;
  start_date: string;
  quote_date: string;
  description: string;
  ers_country: string | null;
  ers_code: string | null;
}

export interface LocationGroupMember {
  id: Generated<number>;
  group_uic_code: string;
  end_date: string;
  member_uic_code: string;
  member_crs_code: string;
}

export interface LocationRailcard {
  id: Generated<number>;
  uic_code: string;
  railcard_code: string;
  end_date: string;
}

export interface LocationSynonym {
  id: Generated<number>;
  uic_code: string;
  end_date: string;
  start_date: string;
  description: string;
}

export interface Log {
  id: Generated<number>;
  filename: string | null;
  processed: string | null;
}

export interface LondonRoute {
  id: Generated<number>;
  route_code: string;
  london_marker: number;
}

export interface LondonStation {
  id: Generated<number>;
  crs_code: string;
  lt_marker: number;
  xlondon_marker: number;
}

export interface Map {
  id: Generated<number>;
  map_identifier: string;
}

export interface NewStation {
  id: Generated<number>;
  nfm64_station_code: string;
  new_station_code: string;
  start_date: string;
  end_date: string;
}

export interface Nfm64 {
  id: Generated<number>;
  origin: string;
  destination: string;
  route_code: string;
  ticket_code: string;
  price: number;
}

export interface NonDerivableFare {
  id: Generated<number>;
  origin_code: string;
  destination_code: string;
  route_code: string | null;
  railcard_code: string;
  ticket_code: string;
  nd_record_type: string;
  end_date: string;
  start_date: string;
  quote_date: string;
  suppress_mkr: number;
  adult_fare: number | null;
  child_fare: number | null;
  restriction_code: string | null;
  composite_indicator: string;
  cross_london_ind: number;
  ps_ind: string;
}

export interface NonDerivableFareOverride {
  id: Generated<number>;
  origin_code: string;
  destination_code: string;
  route_code: string | null;
  railcard_code: string;
  ticket_code: string;
  nd_record_type: string;
  end_date: string;
  start_date: string;
  quote_date: string;
  suppress_mkr: number;
  adult_fare: number | null;
  child_fare: number | null;
  restriction_code: string | null;
  composite_indicator: string | null;
  cross_london_ind: number | null;
  ps_ind: string | null;
}

export interface NonStandardDiscount {
  id: Generated<number>;
  origin_code: string | null;
  destination_code: string | null;
  route_code: string | null;
  railcard_code: string | null;
  ticket_code: string | null;
  end_date: string;
  start_date: string;
  quote_date: string;
  use_nlc: string | null;
  adult_nodis_flag: string;
  adult_add_on_amount: number | null;
  adult_rebook_flag: string;
  child_nodis_flag: string;
  child_add_on_amount: number | null;
  child_rebook_flag: string;
}

export interface Package {
  id: Generated<number>;
  package_code: string;
  end_date: string;
  start_date: string;
  quote_date: string;
  restriction_code: string | null;
  origin_facilities: string | null;
  destination_facilities: string | null;
}

export interface PackageSupplement {
  id: Generated<number>;
  package_code: string;
  end_date: string;
  supplement_code: string;
  direction: string;
  pack_number: string;
  origin_facility: string | null;
  dest_facility: string | null;
}

export interface PermittedRoute {
  id: Generated<number>;
  start_routeing_point: string;
  end_routeing_point: string;
  map_code: string;
}

export interface PhysicalStation {
  id: Generated<number>;
  station_name: string;
  cate_interchange_status: number | null;
  tiploc_code: string;
  crs_reference_code: string | null;
  crs_code: string | null;
  easting: number | null;
  northing: number | null;
  minimum_change_time: number;
}

export interface Railcard {
  id: Generated<number>;
  railcard_code: string;
  end_date: string;
  start_date: string;
  quote_date: string;
  holder_type: string;
  description: string;
  restricted_by_issue: number;
  restricted_by_area: number;
  restricted_by_train: number;
  restricted_by_date: number;
  master_code: string | null;
  display_flag: string;
  max_passengers: number;
  min_passengers: number;
  max_holders: number;
  min_holders: number;
  max_acc_adults: number;
  min_acc_adults: number;
  max_adults: number;
  min_adults: number;
  max_children: number;
  min_children: number;
  price: number | null;
  discount_price: number | null;
  validity_period: string | null;
  last_valid_date: string | null;
  physical_card: number;
  capri_ticket_type: string | null;
  adult_status: string | null;
  child_status: string | null;
  aaa_status: string | null;
}

export interface RailcardMinimumFare {
  id: Generated<number>;
  railcard_code: string;
  ticket_code: string;
  end_date: string;
  start_date: string;
  minimum_fare: number;
}

export interface RestrictionDate {
  id: Generated<number>;
  cf_mkr: string;
  start_date: string;
  end_date: string;
  atb_desc: string | null;
}

export interface RestrictionException {
  id: Generated<number>;
  cf_mkr: string;
  exception_code: string;
  description: string;
}

export interface RestrictionHeader {
  id: Generated<number>;
  cf_mkr: string;
  restriction_code: string;
  description: string | null;
  desc_out: string | null;
  desc_ret: string | null;
  type_out: string;
  type_ret: string;
  change_ind: number;
}

export interface RestrictionHeaderDate {
  id: Generated<number>;
  cf_mkr: string;
  restriction_code: string;
  date_from: string;
  date_to: string;
  monday: number;
  tuesday: number;
  wednesday: number;
  thursday: number;
  friday: number;
  saturday: number;
  sunday: number;
  start_date: string | null;
  end_date: string | null;
}

export interface RestrictionRailcard {
  id: Generated<number>;
  cf_mkr: string;
  railcard_code: string;
  sequence_no: string;
  ticket_code: string | null;
  route_code: string | null;
  location: string | null;
  restriction_code: string | null;
  total_ban: number;
}

export interface RestrictionTicketCalendar {
  id: Generated<number>;
  cf_mkr: string;
  ticket_code: string;
  cal_type: string;
  route_code: string | null;
  country_code: string;
  date_from: string;
  date_to: string;
  monday: number;
  tuesday: number;
  wednesday: number;
  thursday: number;
  friday: number;
  saturday: number;
  sunday: number;
  start_date: string | null;
  end_date: string | null;
}

export interface RestrictionTime {
  id: Generated<number>;
  cf_mkr: string;
  restriction_code: string;
  sequence_no: string;
  out_ret: string;
  time_from: string;
  time_to: string;
  arr_dep_via: string;
  location: string | null;
  rstr_type: string;
  train_type: string;
  min_fare_flag: number;
}

export interface RestrictionTimeDate {
  id: Generated<number>;
  cf_mkr: string;
  restriction_code: string;
  sequence_no: string;
  out_ret: string;
  date_from: string;
  date_to: string;
  monday: number;
  tuesday: number;
  wednesday: number;
  thursday: number;
  friday: number;
  saturday: number;
  sunday: number;
  start_date: string | null;
  end_date: string | null;
}

export interface RestrictionTimeToc {
  id: Generated<number>;
  cf_mkr: string;
  restriction_code: string;
  sequence_no: string;
  out_ret: string;
  toc_code: string;
}

export interface RestrictionTrain {
  id: Generated<number>;
  cf_mkr: string;
  restriction_code: string;
  train_no: string;
  out_ret: string;
  quota_ind: string;
  sleeper_ind: string;
}

export interface RestrictionTrainDate {
  id: Generated<number>;
  cf_mkr: string;
  restriction_code: string;
  train_no: string;
  out_ret: string;
  date_from: string;
  date_to: string;
  monday: number;
  tuesday: number;
  wednesday: number;
  thursday: number;
  friday: number;
  saturday: number;
  sunday: number;
  start_date: string | null;
  end_date: string | null;
}

export interface RestrictionTrainQuota {
  id: Generated<number>;
  cf_mkr: string;
  restriction_code: string;
  train_no: string;
  out_ret: string;
  location: string;
  quota_ind: string | null;
  arr_dep: string;
}

export interface Route {
  id: Generated<number>;
  route_code: string;
  end_date: string;
  start_date: string;
  quote_date: string;
  description: string;
  atb_desc_1: string | null;
  atb_desc_2: string | null;
  atb_desc_3: string | null;
  atb_desc_4: string | null;
  cc_desc: string;
  aaa_desc: string | null;
  uts_mode: string;
  uts_zone_1: number;
  uts_zone_2: number;
  uts_zone_3: number;
  uts_zone_4: number;
  uts_zone_5: number;
  uts_zone_6: number;
  uts_north: string;
  uts_east: string;
  uts_south: string;
  uts_west: string;
}

export interface RouteData {
  id: Generated<number>;
  route_code: string;
  entry_type: string;
  crs_code: string | null;
  group_mkr: number;
  mode_code: string | null;
  toc_id: string | null;
}

export interface RouteLocation {
  id: Generated<number>;
  route_code: string;
  end_date: string;
  admin_area_code: string;
  nlc_code: string;
  crs_code: string | null;
  incl_excl: string;
}

export interface RouteingNode {
  id: Generated<number>;
  node: string;
}

export interface RouteingPoint {
  id: Generated<number>;
  routeing_point: string;
}

export interface Rover {
  id: Generated<number>;
  rover_code: string;
  end_date: string;
  start_date: string;
  quote_date: string;
  description: string;
  ticket_desc: string;
  capri_ticket_code: string | null;
  rover_accounting_code: string;
  days_travel: number;
  months_valid: number;
  days_valid: number;
}

export interface RoverPrice {
  id: Generated<number>;
  rover_code: string;
  end_date: string;
  railcard_code: string;
  rover_class: number;
  adult_fare: number | null;
  child_fare: number | null;
  restriction_code: string | null;
}

export interface Schedule {
  id: Generated<number>;
  train_uid: string;
  runs_from: string;
  runs_to: string;
  monday: number;
  tuesday: number;
  wednesday: number;
  thursday: number;
  friday: number;
  saturday: number;
  sunday: number;
  bank_holiday_running: number;
  train_status: string | null;
  train_category: string | null;
  train_identity: string | null;
  headcode: string | null;
  course_indicator: string;
  profit_center: string | null;
  business_sector: string | null;
  power_type: string | null;
  timing_load: string | null;
  speed: string | null;
  operating_chars: string | null;
  train_class: string | null;
  sleepers: string | null;
  reservations: string | null;
  connect_indicator: string | null;
  catering_code: string | null;
  service_branding: string | null;
  stp_indicator: string;
}

export interface ScheduleExtra {
  id: Generated<number>;
  schedule: number;
  traction_class: string | null;
  uic_code: string | null;
  atoc_code: string;
  applicable_timetable_code: string;
  retail_train_id: string | null;
  source: string | null;
}

export interface ServiceChange {
  id: Generated<number>;
  stop: number;
  location: string;
  suffix: number | null;
  train_category: string | null;
  train_identity: string | null;
  headcode: string | null;
  course_indicator: string;
  profit_center: string | null;
  business_sector: string | null;
  power_type: string | null;
  timing_load: string | null;
  speed: string | null;
  operating_chars: string | null;
  train_class: string | null;
  sleepers: string | null;
  reservations: string | null;
  connect_indicator: string | null;
  catering_code: string | null;
  service_branding: string | null;
  traction_class: string | null;
  uic_code: string | null;
  retail_train_id: string | null;
}

export interface StationCluster {
  id: Generated<number>;
  cluster_id: string;
  cluster_nlc: string;
  end_date: string;
  start_date: string;
}

export interface StationGroup {
  id: Generated<number>;
  station_group_id: string;
  main_station: string;
}

export interface StationLink {
  id: Generated<number>;
  start_station: string;
  end_station: string;
  distance: number;
}

export interface StationRouteingPoint {
  id: Generated<number>;
  station_identifier: string;
  routeing_point_1: string | null;
  routeing_point_2: string | null;
  routeing_point_3: string | null;
  routeing_point_4: string | null;
  station_group_id: string | null;
}

export interface Status {
  id: Generated<number>;
  status_code: string;
  end_date: string;
  start_date: string;
  atb_desc: string | null;
  cc_desc: string | null;
  uts_code: string;
  first_single_max_flat: number | null;
  first_return_max_flat: number | null;
  std_single_max_flat: number | null;
  std_return_max_flat: number | null;
  first_lower_min: number | null;
  first_higher_min: number | null;
  std_lower_min: number | null;
  std_higher_min: number | null;
  fs_mkr: number;
  fr_mkr: number;
  ss_mkr: number;
  sr_mkr: number;
}

export interface StatusDiscount {
  id: Generated<number>;
  status_code: string;
  end_date: string;
  discount_category: number;
  discount_indicator: string;
  discount_percentage: number;
}

export interface StopTime {
  id: Generated<number>;
  schedule: number;
  location: string;
  suffix: number | null;
  scheduled_arrival_time: string | null;
  scheduled_departure_time: string | null;
  scheduled_pass_time: string | null;
  public_arrival_time: string | null;
  public_departure_time: string | null;
  platform: string | null;
  line: string | null;
  path: string | null;
  activity: string;
  engineering_allowance: string | null;
  pathing_allowance: string | null;
  performance_allowance: string | null;
}

export interface Supplement {
  id: Generated<number>;
  supplement_code: string;
  end_date: string;
  start_date: string;
  quote_date: string;
  description: string;
  short_desc: string;
  suppl_type: string;
  price: number;
  cpf_ticket_type: string | null;
  min_group_size: number;
  max_group_size: number;
  per_leg_or_dir: string;
  class_type: string;
  capri_code: string | null;
  sep_tkt_ind: string;
  resvn_type: string;
  sundry_code: string | null;
}

export interface SupplementOverride {
  id: Generated<number>;
  supplement_code: string;
  end_date: string;
  overridden_supplement: string;
}

export interface SupplementRule {
  id: Generated<number>;
  rule_number: number;
  end_date: string;
  start_date: string;
  quote_date: string;
  train_uid: string | null;
  train_uid_desc: string | null;
  fare_class: string;
  quota: string;
  weekend_first: string;
  silver_standard: string;
  railcard: string;
  catering_code: string;
  sleeper: string;
  accom_class: string;
  status: string;
  reservation_status: string | null;
  sectors: string | null;
}

export interface SupplementRuleApplies {
  id: Generated<number>;
  rule_number: number;
  end_date: string;
  ie_marker: string;
  condition_type: string;
  ie_code: string;
}

export interface SupplementRuleSupplement {
  id: Generated<number>;
  rule_number: number;
  end_date: string;
  supplement_code: string;
  om_flag: string;
}

export interface TicketType {
  id: Generated<number>;
  ticket_code: string;
  end_date: string;
  start_date: string;
  quote_date: string;
  description: string;
  tkt_class: number;
  tkt_type: string;
  tkt_group: string;
  last_valid_day: string;
  max_passengers: number;
  min_passengers: number;
  max_adults: number;
  min_adults: number;
  max_children: number;
  min_children: number;
  restricted_by_date: number;
  restricted_by_train: number;
  restricted_by_area: number;
  validity_code: string;
  atb_description: string;
  lul_xlondon_issue: number;
  reservation_required: string;
  capri_code: string;
  lul_93: number | null;
  uts_code: string;
  time_restriction: number | null;
  free_pass_lul: number | null;
  package_mkr: string;
  fare_multiplier: number;
  discount_category: number;
}

export interface TicketValidity {
  id: Generated<number>;
  validity_code: string;
  end_date: string;
  start_date: string;
  description: string;
  out_days: number;
  out_months: number;
  ret_days: number;
  ret_months: number;
  ret_after_days: number;
  ret_after_months: number;
  ret_after_day: string | null;
  break_out: number;
  break_in: number;
  out_description: string;
  rtn_description: string;
}

export interface Tiploc {
  id: Generated<number>;
  tiploc_code: string;
  capitals: string;
  nalco: string;
  nlc_check_character: string;
  tps_description: string | null;
  stanox: string;
  po_mcp_code: number;
  crs_code: string | null;
  description: string | null;
}

export interface Toc {
  id: Generated<number>;
  toc_id: string;
  toc_name: string;
  active: number;
}

export interface TocFare {
  id: Generated<number>;
  fare_toc_id: string;
  toc_id: string | null;
  fare_toc_name: string;
}

export interface TocInterchange {
  id: Generated<number>;
  crs: string;
  from_toc: string;
  to_toc: string;
  time: number;
}

export interface TocSpecificTicket {
  id: Generated<number>;
  ticket_code: string;
  restriction_code: string | null;
  restriction_flag: string;
  direction: string;
  toc_id: string | null;
  toc_type: string;
  end_date: string;
  start_date: string;
  sleeper_mkr: number;
  inc_exc_stock: string;
  stock_list: string | null;
}

export interface ZSchedule {
  id: Generated<number>;
  train_uid: string;
  runs_from: string;
  runs_to: string;
  monday: number;
  tuesday: number;
  wednesday: number;
  thursday: number;
  friday: number;
  saturday: number;
  sunday: number;
  bank_holiday_running: number;
  train_status: string | null;
  train_category: string | null;
  train_identity: string | null;
  headcode: string | null;
  course_indicator: string | null;
  profit_center: string | null;
  business_sector: string | null;
  power_type: string | null;
  timing_load: string | null;
  speed: string | null;
  operating_chars: string | null;
  train_class: string | null;
  sleepers: string | null;
  reservations: string | null;
  connect_indicator: string | null;
  catering_code: string | null;
  service_branding: string | null;
  stp_indicator: string;
}

export interface ZScheduleExtra {
  id: Generated<number>;
  schedule: number;
  atoc_code: string | null;
}

export interface ZStopTime {
  id: Generated<number>;
  z_schedule: number;
  location: string;
  scheduled_arrival_time: string | null;
  scheduled_departure_time: string | null;
  scheduled_pass_time: string | null;
  public_arrival_time: string | null;
  public_departure_time: string | null;
  platform: string | null;
  line: string | null;
  path: string | null;
  activity: string;
  engineering_allowance: string | null;
  pathing_allowance: string | null;
  performance_allowance: string | null;
}

export interface Database {
  additional_fixed_link: AdditionalFixedLink;
  advance_ticket: AdvanceTicket;
  alias: Alias;
  association: Association;
  easement: Easement;
  easement_detail: EasementDetail;
  easement_exception: EasementException;
  easement_location: EasementLocation;
  easement_text: EasementText;
  easement_toc: EasementToc;
  fare: Fare;
  fixed_link: FixedLink;
  flow: Flow;
  link: Link;
  location: Location;
  location_association: LocationAssociation;
  location_group: LocationGroup;
  location_group_member: LocationGroupMember;
  location_railcard: LocationRailcard;
  location_synonym: LocationSynonym;
  log: Log;
  london_route: LondonRoute;
  london_station: LondonStation;
  map: Map;
  new_station: NewStation;
  nfm64: Nfm64;
  non_derivable_fare: NonDerivableFare;
  non_derivable_fare_override: NonDerivableFareOverride;
  non_standard_discount: NonStandardDiscount;
  package: Package;
  package_supplement: PackageSupplement;
  permitted_route: PermittedRoute;
  physical_station: PhysicalStation;
  railcard: Railcard;
  railcard_minimum_fare: RailcardMinimumFare;
  restriction_date: RestrictionDate;
  restriction_exception: RestrictionException;
  restriction_header: RestrictionHeader;
  restriction_header_date: RestrictionHeaderDate;
  restriction_railcard: RestrictionRailcard;
  restriction_ticket_calendar: RestrictionTicketCalendar;
  restriction_time: RestrictionTime;
  restriction_time_date: RestrictionTimeDate;
  restriction_time_toc: RestrictionTimeToc;
  restriction_train: RestrictionTrain;
  restriction_train_date: RestrictionTrainDate;
  restriction_train_quota: RestrictionTrainQuota;
  route: Route;
  route_data: RouteData;
  route_location: RouteLocation;
  routeing_node: RouteingNode;
  routeing_point: RouteingPoint;
  rover: Rover;
  rover_price: RoverPrice;
  schedule: Schedule;
  schedule_extra: ScheduleExtra;
  service_change: ServiceChange;
  station_cluster: StationCluster;
  station_group: StationGroup;
  station_link: StationLink;
  station_routeing_point: StationRouteingPoint;
  status: Status;
  status_discount: StatusDiscount;
  stop_time: StopTime;
  supplement: Supplement;
  supplement_override: SupplementOverride;
  supplement_rule: SupplementRule;
  supplement_rule_applies: SupplementRuleApplies;
  supplement_rule_supplement: SupplementRuleSupplement;
  ticket_type: TicketType;
  ticket_validity: TicketValidity;
  tiploc: Tiploc;
  toc: Toc;
  toc_fare: TocFare;
  toc_interchange: TocInterchange;
  toc_specific_ticket: TocSpecificTicket;
  z_schedule: ZSchedule;
  z_schedule_extra: ZScheduleExtra;
  z_stop_time: ZStopTime;
}
