import config, {FeedConfig} from "../../config";
import {Field} from "../feed/field/Field";
import {Record} from "../feed/record/Record";
import {FieldType, getFieldType} from "./SchemaDialect";
import {LOG_TABLE} from "./SchemaBuilder";

/**
 * Kysely needs a type for every table to give any type safety at all, and the feed definitions in config
 * already describe every column. Rather than introspect a live database, which would lose the distinction
 * between a date and a string as soon as it went near SQLite, the types are generated from those
 * definitions. Run npm run generate-types after changing a feed definition.
 */
export function generateTypes(): string {
  const tables = getTables();
  const interfaces = [...tables.entries()].map(([name, columns]) => getInterface(name, columns));
  const entries = [...tables.keys()].map(name => `  ${name}: ${getInterfaceName(name)};`);

  return `// Generated by npm run generate-types from the feed definitions in config. Do not edit by hand.

import {Generated} from "kysely";

${interfaces.join("\n\n")}

export interface Database {
${entries.join("\n")}
}
`;
}

type Column = { type: string, optional: boolean };
type Columns = Map<string, Column>;

/**
 * Every table the importer creates, in a stable order, with the columns merged across the feeds that
 * define them
 */
function getTables(): Map<string, Columns> {
  const tables = new Map<string, Columns>();

  for (const record of getRecords()) {
    const existing = tables.get(record.name);

    tables.set(record.name, existing ? mergeColumns(existing, getColumns(record)) : getColumns(record));
  }

  tables.set(LOG_TABLE, new Map(Object.entries({
    // these mirror createLogSchema
    id: { type: "Generated<number>", optional: false },
    filename: { type: "string | null", optional: false },
    processed: { type: "string | null", optional: false }
  })));

  return new Map([...tables.entries()].sort(([a], [b]) => a.localeCompare(b)));
}

function getRecords(): Record[] {
  const feeds: FeedConfig[] = Object.values(config);

  return feeds.flatMap(feed => Object.values(feed).flatMap(file => file.recordTypes));
}

function getColumns(record: Record): Columns {
  const columns: Columns = new Map([["id", { type: "Generated<number>", optional: false }]]);

  for (const [name, field] of Object.entries(record.fields)) {
    columns.set(name, { type: getColumnType(field), optional: false });
  }

  return columns;
}

/**
 * The fares and routeing feeds both define a location table with different columns, and whichever is
 * imported last wins. Columns that only some definitions have are marked optional so that either shape
 * type checks.
 */
function mergeColumns(a: Columns, b: Columns): Columns {
  const merged: Columns = new Map();

  for (const [name, column] of [...a, ...b]) {
    const other = a.has(name) && b.has(name);
    const existing = merged.get(name);

    merged.set(name, {
      type: existing && existing.type !== column.type ? `${existing.type} | ${column.type}` : column.type,
      optional: !other
    });
  }

  return merged;
}

function getColumnType(field: Field): string {
  const type = getTypeScriptType(getFieldType(field));

  return field.nullable ? `${type} | null` : type;
}

function getTypeScriptType(field: FieldType): string {
  switch (field.type) {
    // dates and times are read as strings so that they do not depend on the timezone of the reader
    case "text": return "string";
    case "date": return "string";
    case "time": return "string";
    // the feed parses booleans to 1 and 0 rather than true and false
    case "boolean": return "number";
    case "int": return "number";
    case "double": return "number";
    case "foreignKey": return "number";
  }
}

function getInterface(name: string, columns: Columns): string {
  const properties = [...columns.entries()].map(
    ([column, { type, optional }]) => `  ${column}${optional ? "?" : ""}: ${type};`
  );

  return `export interface ${getInterfaceName(name)} {\n${properties.join("\n")}\n}`;
}

function getInterfaceName(table: string): string {
  return table.split("_").map(part => part.charAt(0).toUpperCase() + part.slice(1)).join("");
}
